修复check_dependencies导致model_adapter入口启动崩溃
Co-authored-by: ascend-robot<zhongyuanke@huawei.com>



# message auto-generated for no-merge-commit merge:
!423 merge ms1_26_1_0 into 26.1.0

修复check_dependencies导致model_adapter入口启动崩溃

Created-by: weixin_43113933
Commit-by: pengzhipin;ascend-robot
Merged-by: ascend-robot
Description: # PR Template

Thanks for your contribution; we appreciate it a lot. The following instructions will make your pull request healthier and help you get feedback more easily. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.
感谢您的贡献，我们非常重视。以下说明将使您的拉取请求更健康，更易于获得反馈。如果您不理解某些项目，请不要担心，只需提交拉取请求并从维护人员那里寻求帮助即可。

**PR Type / PR类型**

- [ ] Feature（功能新增）
- [ ] Bugfix（Bug 修复）
- [ ] Docs（文档更新）
- [ ] CI/CD（持续集成/持续部署）
- [ ] Refactor（代码重构）
- [ ] Perf（性能优化）
- [ ] Test-Cases（测试用例更新）
- [ ] Other（其他）

## 🔍 Motivation / 变更动机

**Please describe the motivation of this PR and the goal you want to achieve through this PR.**
**请描述您的拉取请求的动机和您希望通过此拉取请求实现的目标。**

修复model_adapter报错:AttributeError: module 'tensor_cast.utils' has no attribute 'check_dependencies'

------

## 📝 Modification / 修改内容

**Please briefly describe what modification is made in this PR.**
**请简要描述此拉取请求中进行的修改。**

删除 main() 中对 check_dependencies 的调用

------

## 📐 Associated Test Results / 关联测试结果

**Please provide the related test results, such as test reports, etc.**
**请提供相关测试结果，例如测试报告等。**

![image.png](https://raw.gitcode.com/user-images/assets/8428112/ec8ebb8e-dd1b-4dbf-840a-730f2dc88414/image.png 'image.png')

------

## 🌟 Use cases (Optional) / 使用案例（可选）

**If this PR introduces a new feature, it is better to list some use cases here and update the documentation.**
**如果此拉取请求引入了新功能，最好在此处列出一些用例并更新文档。**

------

## ✅ Checklist / 检查列表

**Before PR**:

- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests. / 修复的 Bug 已完全由单元测试覆盖，导致 Bug 的情况应在单元测试中添加。
- [ ] The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness. / 此拉取请求中的修改已完全由单元测试覆盖。如果不是，请添加更多单元测试以确保正确性。
- [ ] All relevant documentation (API docs, docstrings, example tutorials) has been updated to reflect these changes. / 所有相关文档（API 文档、文档字符串、示例教程）已更新以反映这些更改。
- [ ] Please ensure code files contain no Chinese comments. / 请保证代码文件中不含中文注释。

------


See merge request: Ascend/msmodeling!423